<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationDefaultFont>Segoe UI, 10pt</ApplicationDefaultFont>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/BatteryCharge.App/BatteryCharge.App.csproj" />
  </ItemGroup>
</Project>
